### ISSUE TITLE
Broken quests (missing items)

### ISSUE THREAD

**Issue by Tom4455** [Tenchu98/Realism#1]
In the ae2 tab theres these 3 quests
![image](https://user-images.githubusercontent.com/8618678/93901132-1a302400-fcee-11ea-8eb9-8a92f837e940.png)

In the buildcraft tab theres this quest which wants a diamond gear from thermal foundation, which dosent seem to be in the pack
![image](https://user-images.githubusercontent.com/8618678/93901544-89a61380-fcee-11ea-87b6-52cc511ec482.png)

I dont know whats wrong with the first 3, I assume thermal foundation was in a earlier build of the pack?

**Comment by Tenchu98** [comment]
Which version are you on? I believe these were fixed in the latest version.

**Comment by Tom4455** [comment]
1.0.8b, I dont see anything later than that

**Comment by Tenchu98** [comment]
Fixed in 1.0.9
