### ISSUE TITLE
Items to remove.

### ISSUE THREAD

**Issue by ghost** [Tenchu98/Realism#12]
In this post Ill gradually add all items that dont have a crafting recipe or are obsolete.

1. Steel grit - Immersive Engi
2. Steel dust - Vulpes lib
3. Steel dust - Base metals
4. Steel dust - Magneticraft
5. Steel Gear - Base metals
6. Steel dust - TechStack's
7. Iron dust - TechStack's
8. Carbon dust - TechStack's
9. Ender dust - AE2
10.  All Dirty metals from base metals
11. Pulsating dust - Forestry
12. Diamond pickaxe -> quarry is uncraftable.

**Comment by Tenchu98** [comment]
Just keep in mind most of those should be oredict with other forms of the same, so their recipes may not show seperately

**Comment by Walior** [comment]
I'm checking them one by one, leaving only the forms that have actual NEI recipes. Im sorry if I add something thats actually craftable but not in there - I dont know all of those mods.

**Comment by Tenchu98** [comment]
Addressed in 1.1.
