### ISSUE TITLE
Iron, Gold, and Diamond Tools have no recipe, but are used in recipes.

### ISSUE THREAD

**Issue by Duckgrass** [Tenchu98/Realism#13]
Things like the block breaker or quarry are uncraftable since the pickaxes need to craft them have no recipe. A fix would be to change those recipes or add back in the tool recipes.

**Comment by Tenchu98** [comment]
Which mod are quarry and block breaker from?

**Comment by westfallk** [comment]
Sorry, the quarry is from buildcraft and block breaker is form Engineer's Decor. However, these are just examples of things that require the different types of tools.

**Comment by Tenchu98** [comment]
Fixed in 1.1.1
