### ISSUE TITLE
mod recomendations

### ISSUE THREAD

**Issue by mangogamr** [Tenchu98/Realism#14]
find me mod (says its 1.16.3 but if you look on the twitch launcher itself it has a 1.12.2 version :/)
https://www.curseforge.com/minecraft/mc-mods/findme

lets you search nearby inventories for items, instead of having to go through every chest and risk missing the item over and over again, just a small qol add on. it is required on both server and client side

reauth mod (also says 1.16.3 but is available for 1.12.2)
https://www.curseforge.com/minecraft/mc-mods/reauth
helps if you get an invalid login session, instead of relaunching the whole pack, is client sided, and added to my file, but nice to have in the pack by default

**Comment by Tenchu98** [comment]
Reauth is in the next version, the pack has simple storage network for the other one

**Comment by Tenchu98** [comment]
I appreciate the recommendations though and am constantly looking for realistic style mods to help improve the pack

**Comment by mangogamr** [comment]
oof, thank you

**Comment by mangogamr** [comment]
i would also recommend ore excavation, but i know that wont go lol

**Comment by Tenchu98** [comment]
I am looking for help with another pack that is the flipside of this one. It's all fantasy and magic, if you wanted to help with that one

**Comment by mangogamr** [comment]
sure, i can try to give soem input, im eveofdeath on the mmcc discord server, msg me adn we can chat on discord a bit maybe?
im on the realism server rigth now as well, im mangogamr

**Comment by Tenchu98** [comment]
https://github.com/Tenchu98/Fantasy
