### ISSUE TITLE
Starting Singleplayer Crashes Game

### ISSUE THREAD

**Issue by Jethrootje** [Tenchu98/Realism#2]
If i start up a Singleplayer world it just crashes, and if you start up the modpack it isn't rsponsive, if you change the Video Settings (GUI Scale) the starting menu changes too.

**Comment by Tenchu98** [comment]
Can you send a crash report?
How much ram did you give it?
The gui should stick to the left side but I can double check it later.

**Comment by Jethrootje** [comment]
I've been trying to find where my Minecraft Modpacks are located so i can find the crashreport but i can't find it.
It has 10GB Ram on it if i'm correct so that's enough.

**Comment by Tenchu98** [comment]
Are you using twitch? If so under the gear icon the should be an option to open the folder

**Comment by Tenchu98** [comment]
If multimc, right click the pack and choose open minecraft folder

**Comment by Jethrootje** [comment]
Ah yeah i see, it says crashlog not found.

**Comment by Jethrootje** [comment]
I can share my screen on Discord if you'd like?

**Comment by Tenchu98** [comment]
Also make sure you have java 8, not 11. I made that mistake when I setup linux

**Comment by Tenchu98** [comment]
There should be a crash-logs folder in the minecraft folder

**Comment by Jethrootje** [comment]
I have version 8

**Comment by Jethrootje** [comment]
![image](https://user-images.githubusercontent.com/36591615/97200822-fb6ff200-17b1-11eb-912a-c7082ee1f097.png)

**Comment by Jethrootje** [comment]
I'll try it again and i'll record it.

**Comment by Jethrootje** [comment]
![image](https://user-images.githubusercontent.com/36591615/97201172-6faa9580-17b2-11eb-8ef8-ccdf7511dbe1.png)
This happens for me by the way if i start up the modpack.

**Comment by Tenchu98** [comment]
What version did you download?

**Comment by Jethrootje** [comment]
I just clicked Install, so the latest.

**Comment by Tenchu98** [comment]
That shouldn't be like that with 1.1.0

**Comment by Jethrootje** [comment]
1.1.0b

**Comment by Tenchu98** [comment]
Make sure you have 1.1.0 installed

**Comment by Jethrootje** [comment]
How, i don't see any other versions on Twitch

**Comment by Jethrootje** [comment]
![Uploading image.png…]()

**Comment by Jethrootje** [comment]
![image](https://user-images.githubusercontent.com/36591615/97201476-cb751e80-17b2-11eb-9f44-3f3dbed0c826.png)

**Comment by Jethrootje** [comment]
Oh woops

**Comment by Tenchu98** [comment]
That's the right version

**Comment by Jethrootje** [comment]
Installing, i'll let you know.

**Comment by Jethrootje** [comment]
I'm installing 1.1.0 right now, instead of 1.1.0b

**Comment by Tenchu98** [comment]
The menu shouldn't look like that though

**Comment by Jethrootje** [comment]
![crash](https://user-images.githubusercontent.com/36591615/97202097-78e83200-17b3-11eb-9254-6c31e0ad0912.gif)
This is what happens by the way.

**Comment by Tenchu98** [comment]
Unfortunately I cant read that error

**Comment by Tenchu98** [comment]
What world type did you choos3?

**Comment by Jethrootje** [comment]
It's not really an error it just says:
An unsuspected problem has crashed the game, Our apologies for the inconvenience. Closecode: 0
Standard minecraft crash code

**Comment by Jethrootje** [comment]
I have tried both, multiple times.

**Comment by Tenchu98** [comment]
I dont know why it isnt producing a crash report then

**Comment by Tenchu98** [comment]
Is there anything I side the logs folder?

**Comment by Jethrootje** [comment]
![image](https://user-images.githubusercontent.com/36591615/97202785-599dd480-17b4-11eb-84e3-4f1625e7d7ce.png)

**Comment by Tenchu98** [comment]
Also can you try using multimc and see if it does the same thing? You just download the pack straight from the curseforge page and then choose new instance and add from zip in multimc

**Comment by Tenchu98** [comment]
Post the latest.log pls

**Comment by Jethrootje** [comment]
[2020-10-26-1.log](https://github.com/Tenchu98/Realism/files/5440203/2020-10-26-1.log)

**Comment by Jethrootje** [comment]
1.1.0 crashed too.

**Comment by Jethrootje** [comment]
Gonna download MultiMC now

**Comment by Tenchu98** [comment]
Looks like your planets.xml config file is messed up for some reason, I just love twitch. Let me know if it works in multimc

**Comment by Jethrootje** [comment]
Will do!

**Comment by Jethrootje** [comment]
Same thing happened

**Comment by Jethrootje** [comment]
[2020-10-26-3.log](https://github.com/Tenchu98/Realism/files/5440361/2020-10-26-3.log)

**Comment by Tenchu98** [comment]
Ok I will look into it in more detail when I get home

**Comment by Jethrootje** [comment]
Alright. Let me know

**Comment by Tom4455** [comment]
I'm also crashing when trying to make a world in 1.1.0, loading a old world works fine tho

(Crashlog when making new world_
[hs_err_pid4008.log](https://github.com/Tenchu98/Realism/files/5441079/hs_err_pid4008.log)

**Comment by Tenchu98** [comment]
Ok so there is a corruption on lines 8, and 258 in the planetdef.xml
Editing line 8 to remove the excess text an changing the ae2 ore back to oreosmium should resolve the issue.

This is fixed in the upcoming release.

**Comment by Tenchu98** [comment]
Fixed in 1.1.1
