### ISSUE TITLE
missing recipies/quest error?

### ISSUE THREAD

**Issue by mangogamr** [Tenchu98/Realism#20]
there is a questline for improved backpacks mod. ender bag is a quest, just having a backpack is a quest. there seems to be no recipe for either anymore. also there is a quest for having a jetpack attached to a backpack that gives you a jetpack. so unless you pan for that to be a late game thing that's odd. and when completed it gives you a spare jetpack? why do i need 2 jetpacks, one with a backpack attached? i think there's some error there somewhere, just seems wrong to me

so, missing recipes for ender backpack and normal backpack from improved backpacks
and jetpack with backpack attached gives you spare jetpack maybe error

**Comment by Tenchu98** [comment]
Recipes are still in the pack, please make sure you downloaded the updated tinkeredhegemony.cfg and put it in your configs folder.

quests are being looked into.

**Comment by mangogamr** [comment]
ok, i replaced the file and hopefully it fixes the recipie, but the jetpackj with a backpack attached still confuses me as a quest

**Comment by anoldshoe** [comment]
its not an item, its a achievement: Taking inventory.. in the sky

**Comment by mangogamr** [comment]
yes, but the quest is for that. then it gives you a jetpack, make a jetpack and get a free jetpack basically

thats my thing. why are you giving us a second jetpack

**Comment by Tenchu98** [comment]
This should be fixed in the next update
