### ISSUE TITLE
JEI highlighting buggy on Eggs

### ISSUE THREAD

**Issue by FlyingThunder** [Tenchu98/Realism#21]
![grafik](https://user-images.githubusercontent.com/39583733/97802779-217c1300-1c46-11eb-91de-8fd03697a513.png)

As you can see all the eggs arent highlighted at all, only the unidentified one and two other unrelated items

**Comment by Tenchu98** [comment]
I can look at it, but those are exotic bird eggs. I am not sure if those eggs have any ore dict with normal eggs atm

**Comment by Tenchu98** [comment]
Unfortunately I cant find a way to change those, they are oredict and everything. I suspect it's just a jei glitch.
