### ISSUE TITLE
glow rose recipie issue

### ISSUE THREAD

**Issue by mangogamr** [Tenchu98/Realism#22]
glow roses can be centrifuged in the forestry centrifuge for 2 of the respected dye and a 25 percent chance for a piece of glowstone. but the saphire and iolite glow roses cant, also normally y9u can craft the glow roses to jsut get 2 of the dye. so iolite and saphire glow roses are jsut broken

**Comment by Tenchu98** [comment]
I will look at it before the update, I tried to grab all the Rose's and did each one manually

**Comment by mangogamr** [comment]
ok thank you

**Comment by Tenchu98** [comment]
Fixed in next update
