### ISSUE TITLE
Cannot unlock Buildcraft quest chain.

### ISSUE THREAD

**Issue by n33tfr33k** [Tenchu98/Realism#23]
#### Description:

Cannot unlock the Advanced Technology -> Buildcraft quest chain.  The first quest "Let's get piping" requires the creation of a Wooden Gear of type "buildcraftcore:gear_wood".  However, that recipe only creates a Wooden Gear of type "appliedenergistics2:material" and the quest does not recognize the resulting AE2 Wooden Gear as the required item.

#### Steps to reproduce the issue:

1.  Click on "Let's get piping" quest
2.  View recipe for required item.
3.  Attempt to craft required item

#### What's the expected result?

- A Buildcraft Wooden Gear should be created, or the quest accepts a AE2 Wooden Gear instead.

#### What's the actual result?

- An AE2 Wood Gear is crafted and the quest does not accept it as a Buildcraft Wooden Gear

#### Additional details / screenshot
- Currently running 1.1.2 as this is required to join the server, did not see anything to indicate this issue was resolved in more recent version.

**Comment by Tenchu98** [comment]
Fixed on the official server and fix will be in an upcoming pack update
