### ISSUE TITLE
Stacking Quests

### ISSUE THREAD

**Issue by Tom4455** [Tenchu98/Realism#7]
In the questbook there are two (so far) quests which overlap

![image](https://user-images.githubusercontent.com/8618678/97254156-af4e9d00-1805-11eb-9e25-72a7009f87be.png)
![image](https://user-images.githubusercontent.com/8618678/97254173-b70e4180-1805-11eb-919f-848780d5dd18.png)

its possible to get around this by double tapping shift and typing in the quest name to select it manually but its not great

**Comment by anoldshoe** [comment]
fixed
